### ISSUE TITLE
Koppelen aan server

### ISSUE THREAD

**Issue by itzmich3l** [onno204/fivem-meos#1]
Hi, hoe kan ik dit koppelen aan me FiveM server zodat de boetes zichtbaar zijn in de server kan niks in de config files vinden en hoe kan ik agenten registeren.

**Comment by onno204** [comment]
Hoi @itzmich3l ,
Deze meos is nooit af gemaakt en zal dus ook niet werken. Momenteel is het enige dat werkt in & uitloggen.

Sorry

**Comment by itzmich3l** [comment]
Okay, ik zie namelijk dat meerdere servers dit hebben enig idee waar ik dat vandaan haal want alle meos sites lijken op elkaar.

**Comment by onno204** [comment]
Die zijn allemaal gemaakt door Koen.
Probeer hem op discord te bereiken op: @Koen1997#2008
