### ISSUE TITLE
?

### ISSUE THREAD

**Issue by JochemService** [onno204/fivem-meos#3]
Kan dit worden afgemaakt zonee weet u iemand die dit wel doet die @Koen1997#2008 die accepteert geen vriend verzoeken

**Comment by onno204** [comment]
@JochemService 
Ik zie momenteel geen persoonlijk nut in het afmaken van dit project.
Eventueel kunnen we tot een betalings regeling komen waardoor we allebei blij zijn.
Voormeer info stuur me een berichtje op discord.
Mijn discord: @onno204#2219
